language: java

jdk:
  - openjdk11

env:
  - MAVEN_OPTS=-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn

cache:
  directories:
    - .autoconf
    - $TRAVIS_HOME/.m2

services:
  - docker

addons:
  sonarcloud:
    organization: "openwms-github"

script:
  - sonar-scanner
  - mvn clean package -Prelease -Ddebug.info=true -U -B $MAVEN_OPTS

after_success:
  - docker build -t openwms/org.openwms.common.comm:latest .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
