eureka:
  client:
    healthcheck:
      enabled: true

---
spring:
  profiles: "!ASYNCHRONOUS"

server:
  port: ${owms.driver.connections.port-rest}

---
spring:
  profiles: ASYNCHRONOUS
  main:
    web-application-type: none

owms:
  driver:
    osip:
      err:
        exchange-name: osip
        queue-name: osip-err-queue
        routing-key: osip.err.received
      locu:
        exchange-name: osip
        routing-key: osip.locu.received
      req:
        exchange-name: osip
        routing-key: osip.req.received
      res:
        exchange-name: osip
        queue-name: osip-res-queue
        routing-key: osip.res.received
      sysu:
        exchange-name: osip
        routing-key: osip.sysu.received
      upd:
        exchange-name: osip
        routing-key: osip.upd.received
