spring:
  application:
    name: tcpip-driver
  cloud:
    config:
      fail-fast: true # true means retry
      discovery:
        enabled: false
        service-id: openwms-config
      retry:
        max-attempts: 120
      username: user
      password: sa
      headers:
        protocol: ${owms.cfgsrv.protocol:http}
      enabled: false
  zipkin:
    sender:
      type: web
feign:
  httpclient:
    connection-timeout: 30000
    connection-timer-repeat: 30000
ribbon:
  connectTimeout: 30000
  ReadTimeout: 30000
owms:
  eureka:
    url: http://user:sa@localhost:8761
    zone: ${owms.eureka.url}/eureka/
  srv:
    protocol: http
    hostname: localhost
  config:
    username: user
    password: sa
  driver:
    timezone: "Europe/Berlin"
    serialization: json
    osip:
      enabled: true
      sync-field: "###"
      date-pattern: yyyyMMddHHmmss
      telegram-ending: "\r\n"
    routing-service:
      name: routing-service # is default
      protocol: http # default: http
      username: user # default: user
      password: sa # default: sa
    connections:
      hostname: localhost
      port-rest: 30008
      so-timeout: 300000
      so-receive-buffer-size: 160
      so-send-buffer-size: 160
      identified-by-field: "RECV"

server:
  port: ${owms.driver.connections.port-rest}
  tomcat:
    threads:
      max: 5

eureka:
  client:
    healthcheck:
      enabled: true
    instance-info-replication-interval-seconds: 10 # default is 30
    service-url:
      defaultZone: ${owms.eureka.zone}  # Must be camelCase
  instance:
    secure-port-enabled: false
    non-secure-port-enabled: true
    metadata-map:
      config-protocol: http # The protocol used to access the config server
      username: ${spring.security.user.name:user}
      password: ${spring.security.user.password}
      protocol: ${owms.srv.protocol}
      zone: ${owms.eureka.zone}
    hostname: ${owms.srv.hostname}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    rabbit:
      enabled: false

logging:
  file:
    name: BOOT-COMMON-Comm.log
    path: "/tmp/owms"

---
spring:
  config:
    activate:
      on-profile: ASYNCHRONOUS

owms:
  driver:
    dead-letter:
      exchange-name: dle.driver
      queue-name: driver-dl-queue
    osip:
      err:
        exchange-name: osip
        queue-name: osip-err-queue
        routing-key-in: osip.err.mfc
        routing-key-out: osip.err.ss
      locu:
        exchange-name: osip
        routing-key-out: osip.locu.ss
      req:
        exchange-name: osip
        routing-key-out: osip.req.ss
      res:
        exchange-name: osip
        queue-name: osip-res-queue
        routing-key-in: osip.res.*
      sysu:
        exchange-name: osip
        routing-key-out: osip.sysu.ss
      upd:
        exchange-name: osip
        routing-key-out: osip.upd.ss

management:
  health:
    rabbit:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: DISTRIBUTED
  cloud:
    config:
      discovery:
        enabled: true
      enabled: true

eureka:
  instance:
    statusPageUrl: ${owms.srv.protocol}://${owms.srv.hostname}/info
    healthCheckUrl: ${owms.srv.protocol}://${owms.srv.hostname}/health
    homePageUrl: ${owms.srv.protocol}://${owms.srv.hostname}/

---
spring:
  config:
    activate:
      on-profile: SYNCHRONOUS
  rabbitmq:
    listener:
      direct:
        auto-startup: false
  cloud:
    config:
      discovery:
        enabled: true
      enabled: true

management:
  health:
    rabbit:
      enabled: false

owms:
  driver:
    osip:
      enabled: true
    server:
      port-rest: 30008
server:
  port: ${owms.driver.connections.port-rest}

---
spring:
  config:
    activate:
      on-profile: HEROKU
  main:
    banner-mode: "OFF"
  cloud:
    config:
      headers:
        protocol: ${owms.cfgsrv.protocol:https}
      enabled: true

owms:
  srv:
    protocol: https
    hostname: openwms-tcpip-driver.herokuapp.com

eureka:
  instance:
    secure-port-enabled: true
    non-secure-port-enabled: false
    statusPageUrl: ${owms.srv.protocol}://${owms.srv.hostname}:${server.port}/actuator/info
    healthCheckUrl: ${owms.srv.protocol}://${owms.srv.hostname}:${server.port}/actuator/health
    homePageUrl: ${owms.srv.protocol}://${owms.srv.hostname}:${server.port}/actuator/

---
spring:
  config:
    activate:
      on-profile: TEST
  cloud:
    config:
      discovery:
        enabled: false
      enabled: false

owms:
  driver:
    routing-service:
      name: routing-service # is default
      protocol: http # default: http
      username: user # default: user
      password: sa # default: sa
    connections:
      hostname: 127.0.0.1
      port-rest: 30008
      so-timeout: 200000
      so-receive-buffer-size: 140
      so-send-buffer-size: 140
      identified-by-field: "TEST"
      subsystems:
        - name: SPS01
          inbound:
            mode: server
            hostname: 0.0.0.0
            port: 30001
            so-receive-buffer-size: 200
          outbound:
            mode: client
            hostname: 0.0.0.0
            port: 30002
            so-send-buffer-size: 200
            identified-by-field: "RECV"
            identified-by-value: "SPS01"
        - name: SPS02
          inbound:
            mode: server
            port: 30012
          outbound:
            mode: server
            port: 30011
            identified-by-value: "SPS02"
        - name: SPS03
          duplex:
            mode: server
            hostname: localhost
            port: 30003
            so-timeout: 60000
            so-send-buffer-size: 200
            so-receive-buffer-size: 200
            identified-by-field: "RECV"
            identified-by-value: "SPS03"
        - name: SPS04
          duplex:
            mode: server
            port: 30004
            identified-by-value: "SPS04"
        - name: SPS05
          duplex:
            mode: client
            port: 30005
            identified-by-value: "SPS05"
