eureka:
  client:
    healthcheck:
      enabled: true

---
spring:
  profiles: "!ASYNCHRONOUS"

server:
  port: ${owms.driver.server.port-rest}

---
spring:
  profiles: ASYNCHRONOUS
  main:
    web-environment: false

owms:
  driver:
    err:
      queue-name: err
      exchange-name: osip
      routing-key: tcpip-driver
    locu:
      exchange-name: osip
      routing-key: osip.locu.received
    req:
      exchange-name: osip
      routing-key: osip.req.received
    res:
      queue-name: res
      exchange-name: osip
      routing-key: tcpip-driver
    sysu:
      exchange-name: osip
      routing-key: osip.sysu.received
    upd:
      exchange-name: osip
      routing-key: osip.upd.received
