eureka:
  client:
    healthcheck:
      enabled: true

---
spring:
  profiles: ASYNCHRONOUS

owms:
  driver:
    osip:
      enabled: true
      err:
        exchange-name: osip
        queue-name: osip-err-queue
        routing-key-in: osip.err.mfc
        routing-key-out: osip.err.ss
      locu:
        exchange-name: osip
        routing-key-out: osip.locu.ss
      req:
        exchange-name: osip
        routing-key-out: osip.req.ss
      res:
        exchange-name: osip
        queue-name: osip-res-queue
        routing-key-in: osip.res.*
      sysu:
        exchange-name: osip
        routing-key-out: osip.sysu.ss
      upd:
        exchange-name: osip
        routing-key-out: osip.upd.ss

---
spring:
  profiles: "!ASYNCHRONOUS"
  rabbitmq:
    listener:
      direct:
        auto-startup: false

management:
  health:
    rabbit:
      enabled: false

owms:
  driver:
    osip:
      enabled: true
    server:
      port-rest: 30008
server:
  port: ${owms.driver.connections.port-rest}
